apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebdeployment
  namespace: webapp
  labels:
    app: myweb
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: docker.io/bsanthosha/tomcat:latest-$BUILD_NUMBER
        ports:
        - containerPort: 8080
